### ISSUE TITLE
spacymoji not support Thai language

### ISSUE THREAD

**Issue by wannaphong** [ines/spacymoji#11]
from https://github.com/PyThaiNLP/pythainlp/issues/465, I found spacymoji not support Thai language. Can you advise me?

**Comment by BradKML** [comment]
Emoji is its own language (in Unicode at least), so it might be wise to check how this fails.
> spacymoji only cares about the token text, so you can use it on a blank Language instance (it should work for all available languages!

**Comment by polm** [comment]
Sorry for the delayed reply to this. I think this works without issue now since v3 support was released?

```
import spacy

nlp = spacy.blank("th")
nlp.add_pipe("emoji", first=True)
```

Going to close this since I think it's resolved, but if you're still having issues let us know.
