### ISSUE TITLE
spaCy v3 support: PR 

### ISSUE THREAD

**Issue by buhrmann** [ines/spacymoji#12]
Hi, just to avoid any potential overlapping work... I'm about to finish an update of spacymoji to make it compatible with spacy v3.0, while also attempting to fix a couple of edge cases. I've got this PR on my own fork in case anyone wants to check or help: https://github.com/graphext/spacymoji/pull/2

So far all tests are working. I'll still want to check if I can fix a couple of outstanding upstream issues before making a PR here.

**Comment by granawkins** [comment]
Looking forward to this release!

**Comment by buhrmann** [comment]
This has been merged now (and given a nice makeover by Ines), so closing this.
