### ISSUE TITLE
update to support emoji > 2.0

### ISSUE THREAD

**Issue by lsmith77** [ines/spacymoji#17]
relates to https://github.com/carpedm20/emoji/issues/255

**Comment by bdura** [comment]
Hello @lsmith77, thanks for your suggestion. We'll need to check that this change does not break anything.

**Comment by lsmith77** [comment]
I do suspect that it will require some changes unfortunately to support 2.x, while 1.x might be fine

https://github.com/carpedm20/emoji/blob/master/CHANGES.md#v200-2022-06-30

I would however think that given the relative age of the below 2.x releases it is not a requirement for this package to support those older versions.

**Comment by adrianeboyd** [comment]
Please try out `spacymoji` v3.1.0, which uses `emoji` v2.x.

**Comment by lsmith77** [comment]
yup. works nicely. thx
